Add IssuingEmbossingKit resource
starkinfra/sdk-go pull request #2
Opened 2023-04-10 21:42 UTC by leandro-stark

2023-04-12 19:27 UTC, xavier-stark requested changes
Só identação e o teste do embossing request

2023-04-12 19:27 UTC, xavier-stark commented on starkinfra/issuingembossingkit/issuing_embossing_kit.go
> +//	- Designs [slice of IssuingDesigns]: slice of IssuingDesign objects. ex: "created", "processing", "success", "failed"
aqui temos identação e embaixo temos espaços

2023-06-13 20:13 UTC, leandro-stark commented on README.md
> +        - [EmbossingKit](#query-issuingembossingkits): Create embossing kits
View your current embossing kits

2023-06-13 20:13 UTC, leandro-stark commented on README.md
> +	IssuingEmbossingKit "github.com/starkinfra/sdk-go/starkinfra/issuingembossingkit"
indentação errada

2023-06-13 20:13 UTC, leandro-stark commented on README.md
> +	IssuingEmbossingKit "github.com/starkinfra/sdk-go/starkinfra/issuingembossingkit"
indentação errada

2023-06-13 20:14 UTC, leandro-stark commented on README.md
> +You can get a list of available stocks given some filters.
You can get a list of existing embossing kits given some filters.

2023-06-13 20:14 UTC, leandro-stark commented on README.md
> +Information on a stock may be retrieved by its id.
After its creation, information on an embossing kit may be retrieved by its id.

2023-06-13 20:15 UTC, leandro-stark commented on README.md
> +				PayerId: "123.456.78-90",
indentação erraa

2023-06-13 20:15 UTC, leandro-stark commented on starkinfra/brcodepreview/brcode_preview.go
> +//	- EndToEndId [string]: central bank's unique transaction ID. ex: "E79457883202101262140HHX553UPqeq"
faltou o default

2023-06-13 20:15 UTC, leandro-stark commented on starkinfra/creditnote/credit_note.go
> +//	- NominalAmount [int]: CreditNote value in cents. The nominal_amount parameter is required when amount is not sent. ex: 1234 (= R$ 12.34)
camelCase

2023-06-13 20:16 UTC, leandro-stark commented on starkinfra/issuingembossingkit/issuing_embossing_kit.go
> +	//  	- designIds [slice of strings, default nil]: Slice of designIds to filter retrieved objects. ex: []string{"5656565656565656", "4545454545454545"}
indentação

2023-06-13 20:16 UTC, leandro-stark commented on starkinfra/issuingembossingkit/issuing_embossing_kit.go
> +	//  	- designIds [slice of strings, default nil]: Slice of designIds to filter retrieved objects. ex: []string{"5656565656565656", "4545454545454545"}
indentação

2023-06-13 20:17 UTC, leandro-stark commented on tests/sdk/issuing_embossing_resquest_test.go
> +	paramsQuery["limit"] = rand.Intn(100)
excluir linha

2023-06-13 20:39 UTC, xavier-stark approved these changes

2023-06-13 21:11 UTC, merged